[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0.9"
itertools = "0.10.5"
# num-bigint = "0.4.3"
# num = " 0.4.0"
# rug = "1.17.0"
malachite = "0.3.0"